name: Actions 😎

on:
  pull_request: {}
  push: { branches: [main] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-18.04
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          lfs: true

      # Cache
      - name: Cache
        uses: actions/cache@v2.1.4
        with:
          path: Library
          key: Library

      # Test
      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v2.0-alpha-3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Unity - Builder
        uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          targetPlatform: StandaloneWindows
          versioning: Semantic

      # Output
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
