name: Actions 😎

on:
  pull_request: {}
  push: { branches: [main] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          lfs: true

      # Cache
      - name: Cache
        uses: actions/cache@v2.1.4
        with:
          path: Library
          key: Library

      # Test
      - name: Unity - Test runner
        uses: actions/upload-artifact@v2
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      #Upload artifacts
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts